import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.symbol.Symbol;
import ghidra.program.model.symbol.SymbolIterator;
import ghidra.program.model.symbol.SymbolType;
import ghidra.util.task.TaskMonitor;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.File;

/**
 * Ghidra script to export function names and labels to CSV format for psxrecomp.
 * Output format: address,name (one per line)
 * 
 * Usage in Ghidra: 
 *   1. Open Script Manager (Window -> Script Manager)
 *   2. Click "New Script" -> Java -> paste this code
 *   3. Run script, choose output CSV file
 * 
 * Or run from command line:
 *   analyzeHeadless <project> <project_name> -import <binary> -scriptPath . -postScript ExportFunctionNames.java <output.csv>
 */

public class ExportFunctionNames extends GhidraScript {

    @Override
    protected void run() throws Exception {
        // Ask user for output file
        File outputFile = askFile("Select output CSV file", "Save");
        if (outputFile == null) {
            println("No output file selected. Aborting.");
            return;
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile))) {
            int count = 0;

            // Export functions
            println("Exporting functions...");
            FunctionIterator functions = currentProgram.getFunctionManager().getFunctions(true);
            for (Function func : functions) {
                if (monitor.isCancelled()) break;
                
                String name = func.getName();
                String addr = "0x" + func.getEntryPoint().toString(); // e.g., "0x00021fb8"
                
                // Skip default/auto-generated names like FUN_00021fb8, sub_00021fb8
                if (isAutoGeneratedName(name)) {
                    continue;
                }
                
                writer.println(addr + "," + name);
                count++;
            }

            // Export labels (non-function symbols)
            println("Exporting labels...");
            SymbolIterator symbols = currentProgram.getSymbolTable().getAllSymbols(true);
            for (Symbol sym : symbols) {
                if (monitor.isCancelled()) break;
                
                // Only export labels that are not function symbols
                if (sym.getSymbolType() == SymbolType.LABEL) {
                    String name = sym.getName();
                    String addr = "0x" + sym.getAddress().toString();
                    
                    // Skip auto-generated labels
                    if (isAutoGeneratedName(name)) {
                        continue;
                    }
                    
                    writer.println(addr + "," + name);
                    count++;
                }
            }

            println("Exported " + count + " symbols to " + outputFile.getAbsolutePath());
        }
    }

    private boolean isAutoGeneratedName(String name) {
        // Ghidra auto-generated function names typically start with FUN_, sub_, thunk_, etc.
        // Auto-generated labels often start with LAB_, DAT_, PTR_, etc.
        return name.matches("^(FUN_|sub_|thunk_|LAB_|DAT_|PTR_|UNK_|caseD_|switchD_).*");
    }
}