# ExportFunctionNames.py
# Jython script for Ghidra to export function names and labels to CSV for psxrecomp
# 
# Usage in Ghidra:
#   1. Open Script Manager (Window -> Script Manager)
#   2. Click "New Script" -> Python -> paste this code
#   3. Run script, choose output CSV file
#
# Or from command line:
#   analyzeHeadless <project> <project_name> -import <binary> -scriptPath . -postScript ExportFunctionNames.py <output.csv>

from ghidra.app.script import GhidraScript
from ghidra.program.model.listing import Function
from ghidra.program.model.symbol import Symbol, SymbolType
from ghidra.util.task import TaskMonitor
import java.io.FileWriter
import java.io.PrintWriter
import java.io.File
import re

class ExportFunctionNames(GhidraScript):
    
    def run(self):
        # Ask user for output file
        outputFile = self.askFile("Select output CSV file", "Save")
        if outputFile is None:
            self.println("No output file selected. Aborting.")
            return

        try:
            writer = PrintWriter(FileWriter(outputFile))
            count = 0

            # Export functions
            self.println("Exporting functions...")
            functions = self.currentProgram.getFunctionManager().getFunctions(True)
            for func in functions:
                if self.monitor.isCancelled():
                    break
                
                name = func.getName()
                addr = "0x" + str(func.getEntryPoint())  # e.g., "0x00021fb8"
                
                # Skip default/auto-generated names like FUN_00021fb8, sub_00021fb8
                if self.isAutoGeneratedName(name):
                    continue
                
                writer.println(addr + "," + name)
                count += 1

            # Export labels (non-function symbols)
            self.println("Exporting labels...")
            symbols = self.currentProgram.getSymbolTable().getAllSymbols(True)
            for sym in symbols:
                if self.monitor.isCancelled():
                    break
                
                # Only export labels that are not function symbols
                if sym.getSymbolType() == SymbolType.LABEL:
                    name = sym.getName()
                    addr = "0x" + str(sym.getAddress())
                    
                    # Skip auto-generated labels
                    if self.isAutoGeneratedName(name):
                        continue
                    
                    writer.println(addr + "," + name)
                    count += 1

            self.println("Exported {} symbols to {}".format(count, outputFile.getAbsolutePath()))
        finally:
            if 'writer' in locals():
                writer.close()

    def isAutoGeneratedName(self, name):
        # Ghidra auto-generated function names typically start with FUN_, sub_, thunk_, etc.
        # Auto-generated labels often start with LAB_, DAT_, PTR_, etc.
        pattern = re.compile(r'^(FUN_|sub_|thunk_|LAB_|DAT_|PTR_|UNK_|caseD_|switchD_).*')
        return pattern.match(name) is not None